# Generated by Django 4.1.1 on 2022-09-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('release_date', models.DateField(blank=True)),
                ('first_date_available', models.DateField(auto_now_add=True)),
                ('model', models.CharField(max_length=50)),
                ('asin', models.CharField(max_length=50)),
            ],
        ),
    ]
